services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: eurekadb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: 'diogo'
      MYSQL_PASSWORD: 'SenhaForte123!'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./back
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eurekadb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=diogo
      - SPRING_DATASOURCE_PASSWORD=SenhaForte123!
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    shm_size: '2gb'
volumes:
  mysql_data: